--- 
    - 
      name: "get file server volume claim"
      register: fileserver_volume_claim
      shell: "k get pvc -n {{ k8s_ns }} | grep {{ planet_graph_volume_claim }} | awk '{print $1}'"
    - 
      name: "get file server volume"
      register: fileserver_volume
      shell: "k get pv -n {{ k8s_ns }} | grep {{ planet_graph_volume }} | awk '{print $1}'"
    - 
      name: "remove fileserver pv claim resources"
      shell: "k delete pvc {{ fileserver_volume_claim.stdout }}  -n {{ k8s_ns }}  "
      when: "fileserver_volume_claim.stdout != '' "
    - 
      name: "remove fileserver pv resources"
      shell: "k delete pv {{ fileserver_volume.stdout }}  "
      when: "fileserver_volume.stdout != '' "
    